Add ARM64 support
Open-Shell/Open-Shell-Menu pull request #641
Opened 2021-02-09 15:46 UTC by Mattiwatti

This PR adds ARM64 support to Open-Shell. See also #553 where this feature was requested.

The changes are not spectacularly interesting and mostly consist of adding a third supported platform to the two existing ones. The only part I'm not quite sure about is the FNV hashes of the MSIs that go into the setup; while it seems to work (the installer works on all three platforms for me) it probably wouldn't hurt if someone double-checked this.

Note that WiX has only added support for ARM64 in v3.14.0.3910. This means I've had to raise the required version used in the build script and documentation from 3.7 to 3.14.

2021-02-09 19:47 UTC, ge0rdi commented
> Note that WiX has only added support for ARM64 in v3.14.0.3910

Unfortunately it seems that AppVeyor images contain 3.11 only :(
Maybe there is some way to ask AppVeyor to update it?

2021-02-09 19:51 UTC, ge0rdi commented
> Maybe there is some way to ask AppVeyor to update it?

Actually WiX 3.14 is just development build, not stable one.
So I don't think `AppVeyor` will add such.

So I guess for now we cannot merge this to master.

I'd suggest to not build ARM64 by default. Just add some possibility if one would like to try it.
Once WiX ARM64 support will get stable and into `AppVeyor` images we can enable ARM64 builds by default.

2021-02-09 19:55 UTC, ge0rdi requested changes
Looks good to me 👍 
Pity that WiX ARM64 support is not in stable yet :(

2021-02-09 19:55 UTC, ge0rdi commented on Src/ClassicIE/ClassicIEDLL/ClassicIEDLL.vcxproj.filters
> +</Project>
This looks like unwanted change.

2021-02-09 19:55 UTC, ge0rdi commented on Src/Setup/BuildInstaller.bat
> +candle Setup.wxs -nologo -out Temp\SetupARM64.wixobj -ext WixUIExtension -ext WixUtilExtension -dx64=0 -dARM64=1 -dCS_LANG_FOLDER=%CS_LANG_FOLDER% -dCS_LANG_NAME=%CS_LANG_NAME%
So it seems we cannot do this by default as there is no proper WiX support on `AppVeyor`.
Either just comment it for now. Or add some parameter that could be used when building locally.

2021-02-10 19:31 UTC, Mattiwatti commented on Src/ClassicIE/ClassicIEDLL/ClassicIEDLL.vcxproj.filters
> +</Project>
Thanks. This should be fixed now.

2021-02-10 19:32 UTC, Mattiwatti commented
Re: the AppVeyor build: I agree that it's undesirable to have a build batch file that doesn't work on AppVeyor by default. However I see some problems with the 'optional parameter' approach: the build of `Setup.sln` will fail if the ARM64 MSI is not built, because a required file will be missing to compile the installer resources.

An option could be to make a separate 'Release with ARM64' configuration for the Setup project, so that the default Release configuration includes only the x86 and x64 MSIs, and only the new configuration would include all three MSIs. But this would require some additional changes to the Setup project.

I see another alternative that may work better: while AppVeyor does not support WiX 3.14, it does provide access to `curl` which can be used to download files. We use this at [ScyllaHide](https://github.com/x64dbg/ScyllaHide) to download dependencies that we cannot include on the repository for legal reasons. I've pushed a new commit to test this. Assuming this works, let me know which approach is preferable.

2021-02-11 17:00 UTC, ge0rdi commented
> Assuming this works, let me know which approach is preferable.

Well, I personally don't like idea of using devel version of software just to support very small amount of users.
I also don't like the idea of adding ARM64 version to common installer by default. As it almost doubles its size (from 7MB to 12MB) and vast majority of users will have to download unnecessarily bigger installer (in fact I don't even like the idea of combined x86/x64 installer, but that's another story).

These are my personal views, maybe @coddec, @XenHat have different views on this.

But to be constructive, what about this:

We can keep installer as it was (x86 + x64) and produce separate ARM64 installer (basically just MSI should be enough).
We can push ARM64 as separate artifact to AppVeyor so ARM64 users will be able to test with it.

Only ARM64 build will then use devel version of WiX (that can be downloaded when needed as you proposed).

What do you think?

2021-02-15 23:08 UTC, coddec commented
> > Assuming this works, let me know which approach is preferable.
> 
> Well, I personally don't like idea of using devel version of software just to support very small amount of users.
> I also don't like the idea of adding ARM64 version to common installer by default. As it almost doubles its size (from 7MB to 12MB) and vast majority of users will have to download unnecessarily bigger installer (in fact I don't even like the idea of combined x86/x64 installer, but that's another story).
> 
> These are my personal views, maybe @coddec, @XenHat have different views on this.
> 
> But to be constructive, what about this:
> 
> We can keep installer as it was (x86 + x64) and produce separate ARM64 installer (basically just MSI should be enough).
> We can push ARM64 as separate artifact to AppVeyor so ARM64 users will be able to test with it.
> 
> Only ARM64 build will then use devel version of WiX (that can be downloaded when needed as you proposed).
> 
> What do you think?

I agree with you @ge0rdi 
In fact, It's not rare to see people distribute installers for different architecture, e.g. installerxx_x86.exe installerxx_x86.msi installerxx_x64.exe installerxx_arm.exe etc. You get the idea. So I'll support the idea of separating installers for different architectures if that won't introduce any trouble/huge work load etc.
It saves bandwidth, storage etc. not sure if there's any negative sides.
For ARM, suggestion from @ge0rdi seems fine to me, what do you think? Idea of separating the installers for different architectures and ARM?  @XenHat @Ibuprophen

2021-02-16 20:31 UTC, Mattiwatti commented
Thanks for the feedback. Summarizing, so far it seems like the way forward for ARM64 is to make a separate installer (and maybe even split x86 and x64 into separate installers as well? I'll leave this up to you guys). This is fine by me, and as has been pointed out it will reduce the download size for both binaries.

What should be the preferred way to build the ARM64 setup? Should there be (a) new batch file(s) to create it (think e.g. `__MakeFinalARM64.bat` and `__MakeFinalAllLanguagesARM64.bat`), or should there be some argument that needs to be passed to the existing batch files that determines which version to build? If the latter, I'm assuming the 'no arguments' case should still build the x86 and x64 combined setup, correct? The reason I'm asking is because presumably it is desirable to make AppVeyor produce automated builds of ARM64 as well as x86/x64.

If the answer to the above is 'don't worry about this, someone else will take care of the installer', or 'do this in another PR', that's fine by me too. I mostly wanted to make this PR to add ARM64 support to Open-Shell, not necessarily Open-Shell's installer :) Though I'm OK with doing it if this is desirable.

2021-02-17 10:28 UTC, ge0rdi commented
@Mattiwatti 
First of all thanks for understanding and I personally appreciate the effort done (as there is not much people contributing to this project).

> Should there be (a) new batch file(s) to create it (think e.g. __MakeFinalARM64.bat and __MakeFinalAllLanguagesARM64.bat), or should there be some argument that needs to be passed to the existing batch files that determines which version to build?

I think separate BAT may be easier to do.
But I guess combined script where one can select what should be built will make more sense.

Basically from my POV both ways make sense.

> If the latter, I'm assuming the 'no arguments' case should still build the x86 and x64 combined setup, correct?

Yup. That would make sense, so it will be backward compatible.

Though in case when some argument will be present it probably should mean _list_ of platforms to build.
So supplying `ARM64` will build ARM64 only and supplying `x86 x64 ARM64` will build all platforms.
What do you think?

> The reason I'm asking is because presumably it is desirable to make AppVeyor produce automated builds of ARM64 as well as x86/x64.

Right.

Depending on the way the ARM64 build will be integrated we can modify `appveyor.yml` to build all 3 platforms.

2021-02-21 00:07 UTC, Mattiwatti commented
I've pushed a new commit that separates the x86/x64 installer from the ARM64 one instead of the previous iteration where the setup was combined. The new ARM64 setup can be built with `__MakeFinalARM64.bat` or `__MakeFinalAllLanguagesARM64.bat`, which is equivalent to `__MakeFinal.bat ARM64` or `__MakeFinalAllLanguages.bat ARM64`. So in principle the new batch files are not strictly necessary, since supplying "ARM64" as the optional argument will build the ARM64 setup. But I thought this way would be more obvious to newcomers who are wondering how to compile for a different architecture.
`__MakeFinal[AllLanguages].bat` without arguments will build the combined x86/x64 installer as before.

> Though in case when some argument will be present it probably should mean list of platforms to build. So supplying ARM64 will build ARM64 only and supplying x86 x64 ARM64 will build all platforms.

I agree this would be preferable, but I'll leave this as a "nice to have" TODO for now. I spent some time trying to make this work for generic lists of architecture names (e.g. "x86 x64 ARM64 foo"), but with all the added batch file boilerplate and error checking the batch files (plural, because there are multiple batch files that all need to know which architecture(s) is/are being built) quickly became very unwieldy with most of the lines "wasted" on simply parsing the architecture(s) to build. So I reverted to the simpler method above for now.

2021-07-10 14:25 UTC, XenHat commented
Late to the party here. I agree with the sentiment that architectures should be split. What's the status on this? Waiting for Wix to be stable?

2021-11-27 03:02 UTC, malxau commented
I just bought an ARM64 device and built from Mattiwatti's branch to install.  Is there anything I can do to help move this forward?  Getting it installed from source worked in the end but was a rough experience (I've never built this code before.)

The only thing I encountered is Utility.rc is trying to include the AMD64 binary (so the x86 binary includes the AMD64 one?) In this build sequence though, BuildBinaries.bat only builds ARM64, not AMD64, so the later x86 build fails because it can't find the AMD64 binary.

2022-08-11 20:59 UTC, Ibuprophen commented
I'm neutral about having separate installers as long as it's necessary to have... 

I'll go with the consensus of the team @ge0rdi, @coddec, @XenHat... 

~Ibuprophen

2022-08-12 03:35 UTC, blackcrack commented
@coddec , could Ibuprophen have the "ownerstate" because he is active here and he is every here, have a good character and know what he does..  
best

2022-08-13 16:08 UTC, Mattiwatti commented
OP here.

I see that I've been assigned this issue, as well as that the issue has been given the `Requires & Awaiting Further Info By OP Issuer` tag (among others). I'm not sure what further info is needed at this point.

There is a [pending change request](https://github.com/Open-Shell/Open-Shell-Menu/pull/641#pullrequestreview-586931549) by @ge0rdi, but this comment only mentions that the stable release of WiX did not support ARM64 at the time. WiX still does not support ARM64 (in fact, WiX has not had any new stable releases since 2019). However the ARM64 installer builds fine with the current development release of WiX (v3.14.0.6526). I haven't retested the PR against current master since I no longer have an ARM64 device on hand for this, but I don't see any changes that would cause issues.

If needed I can force push a rebased PR, but other than that I'm not sure what else I can do for this.

2022-08-13 16:14 UTC, XenHat commented
Could @malxau test the latest code ?

2022-08-13 16:18 UTC, XenHat commented
> I'm neutral about having separate installers as long as it's necessary to have...
> 
> I'll go with the consensus of the team @ge0rdi, @coddec, @XenHat...
> 
> ~Ibuprophen

I'm fairly neutral, I'm more concerned about confusing our users with picking AMD64 or ARM64. Maybe an auto-detection in the installer?

2022-08-13 18:29 UTC, blackcrack commented
@Ibuprophen 
and btw, i have no/0 experience/skills in c or arm coding.. only in scripting in bat/cmd and Linux bash sh, Ibu :)  
and i still look anyway this tread Ibu :smiley:

2022-08-13 19:53 UTC, Ibuprophen commented
@blackcrack, my apologies for as I was "brain dead" when I had added the list of reviewers... LOL! 

~Ibuprophen

2022-08-13 23:40 UTC, malxau commented
Fwiw, I rebased on master and rebuilt everything successfully.  Per above, I had to change Src\Setup\Utility\Utility.rc to point to ReleaseARM64\\Utility.exe rather than Release64\\Utility.exe .  Verified that the installer works, and installs the right version.

I used __MakeFinalARM64.bat for this - is there a reason it needs to build x86? If we have two installers anyway, what function does x86 serve here?

Also, I've since upgraded my ARM64 device to Windows 11 (for x64 support) which means I'm not currently running OpenShell and limits the amount of testing I can really perform.  On Windows 11 it's possible to launch the menu via the win key but not by clicking on the start button.

2023-02-28 17:23 UTC, voicenoise commented
Hello i try to install openshell 4.4.189 on a arm device but it end by a black screen. 
Is the any news or a download for a arm version?
Thanks

2023-02-28 22:48 UTC, Ibuprophen commented
When it comes to ARM32/ARM64 (typically on the Tablets with the Windows OS installed), I don't believe that the Open Shell software (as is) will work out too great (personally). 

I believe that Open Shell would require a separate branch (or repo) that would also require some additional (knowledgeable) individuals who would have to work out the coding and such to accommodate these specific architecture types. 

Just a thought... :thinking: 

@ge0rdi? 

~Ibuprophen

2023-03-01 06:47 UTC, malxau commented
I don't think associating tablets with ARM64 matches what's happening today.  It's true that ARM32 Windows was for tablets, but we've come a long way since then.  My device is a very ordinary looking laptop, and a week or so ago, official support for Windows on Apple laptops was announced: https://support.microsoft.com/en-us/windows/options-for-using-windows-11-with-mac-computers-with-apple-m1-and-m2-chips-cd15fd62-9b34-4b78-b0bc-121baa3c568c

I can take care of the ARM64 port, but right now, the experience on Windows 11 is lacking.  If it works well on Intel, it can work well on ARM64.

2023-03-01 17:45 UTC, bonzibudd commented
@malxau I agree. I imagine many more “standard” form factor systems will be adopting ARM in the near future, so it makes sense to adopt this.

2023-04-22 02:07 UTC, BeholdersEye commented
Apple silicon is arm64 and I expect there may be a few people with macbooks who don't like Windows 11's default shell.

2024-11-14 19:41 UTC, Neustradamus commented
Dear @Open-Shell team, @ge0rdi,

Any progress on this PR?

It is linked to:
- https://github.com/Open-Shell/Open-Shell-Menu/issues/553
- https://github.com/Open-Shell/Open-Shell-Menu/pull/641
- https://github.com/Open-Shell/Open-Shell-Menu/pull/1912

cc: @darthmooguy.

2024-11-17 02:00 UTC, XenHat commented
**Revising my statement:** Also in favor of splitting the installers per architectures. It's common these days with Android and other projects. I see no reason to bloat the installer with unneeded code.

2025-04-27 00:06 UTC, ftc2 commented
arm64 is for sure a thing now and is the main way i use windows. i understand the lack of momentum... no one deeply involved in openshell uses arm64.

but has anyone made a build working on win11 arm64 for personal use? if so, could you please just share it here?

2025-04-27 21:34 UTC, malxau commented
Rather than asking for a build, it would be much better to take up this issue and compile from scratch.  All of the tools needed to do so are freely available – all you need is hardware.

Just out of curiosity I picked it up, rebased and built again.  The core issue in this discussion seems moot now, because x86 is using Wix 3.14, so Arm64 isn’t introducing any new requirement.  It also works on Windows 11, so it ran on my device successfully – but I didn’t do any serious testing.

http://www.malsmith.net/download/openshellarm64.msi

Note I’m just a random person though, so this isn’t signed at all.  It’s also only en-us, where trying to build all languages hit an error that I don’t (yet) understand.  If signing or more languages matters to you, I’d suggest building from source.

2025-04-28 02:32 UTC, ftc2 commented
> Rather than asking for a build, it would be much better to take up this issue and compile from scratch. All of the tools needed to do so are freely available – all you need is hardware.

logically, it sounds like you're saying that it's better to not distribute binaries, and i don't agree with that. i think it would be best for the openshell project to officially distribute arm64 bins, but since this has been designated low-priority and does not appear to be gaining any traction, sharing a working build is a huge service to this otherwise underserved population of users.

i was not willing to build it myself, i asked for a build, and i received a build. your build works great. i thank you, and i'm sure several other users will benefit as well.

2025-04-28 06:55 UTC, ge0rdi commented
@Mattiwatti 
Do you think you can rebase this PR to actual master?
I can understand if you are no longer interested in this (in such case I'll try to finalize your changes, giving you the credit ofc).

It seems that WiX 3.14 is already there by default in AppVeyor build images.
And also it seems that there is much more ARM64 devices already.

I think we can build ARM64 by default now.
Though I guess I'd still keep it as separate install package.

2025-05-02 14:24 UTC, ge0rdi approved these changes

2025-05-02 21:24 UTC, ge0rdi commented
There is another build here:
https://ci.appveyor.com/project/passionate-coder/open-shell-menu/builds/51989416/artifacts

Please, use this one for testing.

2025-05-02 21:24 UTC, ge0rdi approved these changes

2025-05-02 21:48 UTC, ftc2 commented
> There is another build here: https://ci.appveyor.com/project/passionate-coder/open-shell-menu/builds/51989416/artifacts
> 
> Please, use this one for testing.

`OpenShellSetup_4_4_196-rikfexxu.exe` does not work for me.

```
Edition	Windows 11 Pro
Version	24H2
OS build	26120.961
Experience	Windows Feature Experience Pack 1000.26100.8.0
Processor	Apple Silicon   3.20 GHz  (6 processors)
Installed RAM	48.0 GB
System type	64-bit operating system, ARM-based processor
```

![image](https://github.com/user-attachments/assets/dbd8684d-47f2-4f98-8992-50a6ee5be1b0)

2025-05-03 05:24 UTC, ge0rdi commented
@ftc2 Could you try to run installer with `extractARM64` parameter from command line?
That should extract ARM64 installer to actual folder.
Does that work?
And does installing such extracted MSI work?

(sorry, I have no ARM64 machine at hand atm)

2025-05-03 06:38 UTC, malxau commented
For what it’s worth, the installer works correctly for me on 23H2/22631.  The installer stub is x86 but it correctly found and installed the arm64 MSI.  I’m quite surprised by that error – I think it’s from pcasvc indicating a known appcompat problem, not an error indicating a corrupt binary or unsupported architecture.  But if that’s true it should affect any Wix 3.14 installer on 26100 arm64.

2025-05-03 07:26 UTC, ge0rdi commented
@ftc2 You also seem to be on _beta Windows channel_, but rather old build. Maybe try to update to latest build to see it that helps?

2025-05-03 08:07 UTC, ge0rdi commented
> is that how you run windows software with params?

Just use the parameter as I wrote without anything else:
`.\OpenShellSetup_4_4_196-rikfexxu.exe extractARM64`

> the build's not that old

Hehe, funny how relative that is. To me a year old Windows is very old ;)

> if you really want, i can make a new vm with the latest win11 arm64 image test it again, though. lmk.

Well, it is up to you how much do you want to test this and spend your time with it.
I'm glad for any help here.

2025-05-03 08:15 UTC, ftc2 commented
ok, i'll make a new vm in the next day or so :)

2025-05-03 08:20 UTC, ftc2 commented
> Just use the parameter as I wrote without anything else:
> `.\OpenShellSetup_4_4_196-rikfexxu.exe extractARM64`

same result as my other attempts (didn't work)

2025-05-03 08:31 UTC, ge0rdi commented
I got access to ARM64 machine with Win11 24H2 and getting the same PCA compatibility issue dialog.
So I can investigate now (hopefully).

2025-05-03 10:55 UTC, ge0rdi commented
Windows (24H2 so far?) seems to have some compatibility block for `OpenShellSetup*.exe` (and hopefully some other conditions).
Most likely because our installer didn't work on ARM64.

It was enough to rename the installer (`OpenShell_4_4_196.exe`) and then it was allowed to run.

Trying to figure out how to deal with this (without changing the name of installer obviously).

2025-05-03 12:18 UTC, ge0rdi commented
![Screenshot 2025-05-03 141427](https://github.com/user-attachments/assets/b646904d-f0ad-433c-8a5e-ed656252cc8c)
I guess we will have to change name of installer (probably no big deal).
Not sure how to contact MS to lift such hard block (for future versions).

2025-05-03 19:16 UTC, ftc2 commented
haha
so my version of windows was actually too new? ;)

2025-05-03 20:19 UTC, malxau commented
Yes.  The block was added April 2024, so I don’t have it.  It looks like StartMenuHelper64.exe (Amd64) was being injected into Explorer on Arm64 systems, causing Explorer to crash, hence the block.  I’ve started an email thread to find the best process to alter or remove it.

2025-05-04 09:04 UTC, ge0rdi commented
> I guess we will have to change name of installer (probably no big deal).

Hmm, this will actually break built-in updater. As it looks for `OpenShellSetup*` asset on releases page.
So for now I will keep the name as it is.
And rather add some notice/warning on releases page that on ARM64 it may be necessary to rename installer before starting it.

> I’ve started an email thread to find the best process to alter or remove it.

Fingers crossed.

2025-05-04 09:10 UTC, ge0rdi approved these changes

2025-05-04 15:26 UTC, malxau commented
I think the advice is to release an ARM64-capable version and let them know the version number so anything above that can be excluded from the check.  As you’ve seen the current block does not have any version restriction, so this still sounds like it will require a Windows Update. On the other hand, note the ARM64 experience doesn’t change – currently users have a block, once an ARM64 build is released they’ll have a block (with a workaround) and it’ll probably take a couple months for the block to be relaxed.

2025-05-06 14:40 UTC, VerizonLover commented
> > I guess we will have to change name of installer (probably no big deal).
> 
> Hmm, this will actually break built-in updater. As it looks for `OpenShellSetup*` asset on releases page. So for now I will keep the name as it is. And rather add some notice/warning on releases page that on ARM64 it may be necessary to rename installer before starting it.
> 
> > I’ve started an email thread to find the best process to alter or remove it.
> 
> Fingers crossed.

It works! Better make another release before the temporary AppVeyor build expires.

2025-05-06 18:14 UTC, ge0rdi commented
@VerizonLover 
Thank you for testing and letting us know.

> Better make another release before the temporary AppVeyor build expires.

There will be official build (available here on github) once this PR gets merged.
I just wanted to see some feedback, whether it works.
So I guess we can merge this soon.

2025-05-07 04:16 UTC, CompilerBreak commented
> ![Screenshot 2025-05-03 141427](https://private-user-images.githubusercontent.com/2453094/440118755-b646904d-f0ad-433c-8a5e-ed656252cc8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDY1OTA1NDAsIm5iZiI6MTc0NjU5MDI0MCwicGF0aCI6Ii8yNDUzMDk0LzQ0MDExODc1NS1iNjQ2OTA0ZC1mMGFkLTQzM2MtOGE1ZS1lZDY1NjI1MmNjOGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA1MDdUMDM1NzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQzOWM1ZDg4NGYwMzU5NTMzMTJiMjBlYzllMDcxZjNjYWQ2MWYwNDM5NDhlMDJmODljY2MyYWQ5MTc1ZmNlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.N3ZCvuQwQUrL0sDjTaN12vCAuZIYgna2D5-I0gFat0Y) I guess we will have to change name of installer (probably no big deal). Not sure how to contact MS to lift such hard block (for future versions).

Hey folks, this got relayed to me, I'm on the Windows arm64 compat team, awesome to see you all adding arm64 support. What version # will this be targeting for support? We can update the blocks. And how would one test this, are you looking to make a pre-release installer version available here? Thanks!

2025-05-07 07:04 UTC, ge0rdi commented
@CompilerBreak Thank you for reaching out ❤️ 

> What version # will this be targeting?

Right now, the plan is to have ARM64 support in version `4.4.196` (next official build).

> And how would one test this, are you looking to make a pre-release installer version available here?

For now there is AppVeyor build from this PR here:
https://ci.appveyor.com/project/passionate-coder/open-shell-menu/builds/51993885/artifacts

Once the PR gets merged (hopefully in few days, I just want to do some more tests) I will prepare official build and publish it as _pre-release_ here on github.
I can let you know once that is available.

2025-05-08 08:14 UTC, merged

2025-05-08 08:36 UTC, ge0rdi commented
@CompilerBreak 
There is official pre-release [4.4.196](https://github.com/Open-Shell/Open-Shell-Menu/releases/tag/v4.4.196) with ARM64 support.